### ISSUE TITLE
Problem With Callibration

### ISSUE THREAD

**Issue by alessandromorra** [duckietown/docs-opmanual_duckiebot#100]
### Context

*What step were you trying in the documentation?*

10.2

*What command line were you running?*

dts calibrate kleinesentlein

### Problem

*What happened?*

error message:

alessandro@tina-remote:~$ dts calibrate kleinesentlein
4INFO:dts:duckietown-shell 3.0.19

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
/home/alessandro/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Duckietown Shell commands version 1.0.6
master18: Pulling from duckietown/rpi-duckiebot-calibration
Digest: sha256:8079c7bcb24587335ddde51862938d81a1f9372fda17d877c4f25a42ff19d06b
Status: Image is up to date for duckietown/rpi-duckiebot-calibration:master18
master18: Pulling from duckietown/rpi-duckiebot-base
Digest: sha256:7271339723f6f4fd1e9208eced9d9caf6c3b6798de5dddafb56610f02d108aec
Status: Image is up to date for duckietown/rpi-duckiebot-base:master18
access control disabled, clients can connect from any host
4Setting ROS_IP to host IP, which is 192.168.1.159
Writing "192.168.1.13 kleinesentlein kleinesentlein.local" into /etc/hosts
Activating ROS with shell: /bin/bash
Set DUCKIETOWN_ROOT to: /home/software
Set PYTHONPATH to: /home/software/catkin_ws/src:/opt/ros/kinetic/lib/python2.7/dist-packages
Activating development environment...
                                
            .....               
          .........             
         .  ..  ....            
         .  ..  ....            
    .  .............            
    ..     ..   ...       ..    
    .     .........    .....    
     . . .......   .........    
    .   .       ...  .......    
           .......... ......    
        . .  ........ .....     
       . ....        .....      
         ................       
           ...........          
                                
********************
Position the checkerboard pattern in front of the Duckiebot and press ENTER.

... logging to /root/.ros/log/cc1aada0-d2db-11e8-a955-b827eb00c3a6/roslaunch-tina-remote-89.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.159:36499/

SUMMARY
========

PARAMETERS
 * /kleinesentlein/decoder_node/publish_freq: 10.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /kleinesentlein/
    intrinsic_calibrator (camera_calibration/cameracalibrator.py)

ROS_MASTER_URI=http://kleinesentlein.local:11311/

process[kleinesentlein/intrinsic_calibrator-1]: started with pid [98]
[kleinesentlein/intrinsic_calibrator-1] process has died [pid 98, exit code -11, cmd /opt/ros/kinetic/lib/camera_calibration/cameracalibrator.py --size 7x5 --square 0.031 image:=/kleinesentlein/camera_node/image/raw camera:=/kleinesentlein/camera_node __name:=intrinsic_calibrator __log:=/root/.ros/log/cc1aada0-d2db-11e8-a955-b827eb00c3a6/kleinesentlein-intrinsic_calibrator-1.log].
log file: /root/.ros/log/cc1aada0-d2db-11e8-a955-b827eb00c3a6/kleinesentlein-intrinsic_calibrator-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
ros-picam
********************
Place the Duckiebot on the calibration patterns and press ENTER.

tls: oversized record received with length 20527
********************
Place the Duckiebot in a lane and press ENTER.

tls: oversized record received with length 20527
********************
To perform the wheel calibration, follow the steps described in the Duckiebook.
http://docs.duckietown.org/DT18/opmanual_duckiebot/out/wheel_calibration.html
You will now be given a container running on the Duckiebot for wheel calibration.

tls: oversized record received with length 20527
Traceback (most recent call last):
  File "/home/alessandro/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 72, in cli_main
    shell.onecmd(cmdline)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/alessandro/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 405, in <lambda>
    do_command_lam = lambda s, w: do_command(klass, s, w)
  File "/home/alessandro/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    cls.command(shell, args)
  File "/home/alessandro/.dt-shell/commands/calibrate/command.py", line 51, in command
    raise Exception(msg)
Exception: An error occurred while running the calibration procedure, please check and try again (1).

*What did you expect to happen?*

the callibration to start...

### System information

Duckietown version: 

- [X] DT18 
- [ ] DT17

Duckiebot version: 

- [X] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [X] Ubuntu 16.04, native installation
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

I also have a problem with https://github.com/duckietown/docs-opmanual_duckiebot/issues/96

### Screenshots

![callibration_error](https://user-images.githubusercontent.com/32458198/47161048-7d8acd80-d2f1-11e8-9cfb-783b05e93b5e.png)

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

**Comment by AleksandarPetrov** [comment]
From the docs:
If Docker exits with the above error when running remote comamnds, the most likely reason is different versions of Docker on your computer and Duckiebot. You can check that by running docker version on both devices. If that is indeed the case, you need to upgrade the Docker binaries on your computer. To do that, follow the official instructions [here](https://docs.docker.com/install/linux/docker-ce/ubuntu/).

@alessandromorra, please close if that solves it

**Comment by alessandromorra** [comment]
@AleksandarPetrov thanks again!

This is the same issue as [Issue_91](https://github.com/duckietown/docs-opmanual_duckiebot/issues/91)
