### ISSUE TITLE
usb drive not found for mounting

### ISSUE THREAD

**Issue by lgulich** [duckietown/docs-opmanual_duckiebot#122]
### Context
D-2, mounting the usb drive with `bash mount_usb`

### Problem
When trying to mount the usb drive with `bash mount_usb` it returns: `mount: special device /dev/sda1 does not exist`

The usb drive used was formatted to FAT32 and worked on other duckiebots

### System information

Duckietown version: 

- [x] DT18 
- [x] DT17

Duckiebot version: 

- [x] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 18.04, virtual machine
- [x] Ubuntu 16.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes
The device cannot be found in /dev, however the kernel does detect it when inserted and it is also visible in `lsblk`. Please find the respective outputs below.

### Screenshots
* Output of `lsblk`:
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda           8:0    1 57.3G  0 disk 
`-sda1        8:1    1 57.3G  0 part 
mmcblk0     179:0    0 14.9G  0 disk 
|-mmcblk0p1 179:1    0   64M  0 part /boot
`-mmcblk0p2 179:2    0 14.8G  0 part /

* Output of `dmesg`:
[ 1881.855062] usb 1-1.3: new high-speed USB device number 11 using dwc_otg
[ 1881.985936] usb 1-1.3: New USB device found, idVendor=0781, idProduct=5595
[ 1881.985951] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1881.985960] usb 1-1.3: Product: Ultra USB 3.0
[ 1881.985968] usb 1-1.3: Manufacturer: SanDisk
[ 1881.985976] usb 1-1.3: SerialNumber: 4C531001510429108364
[ 1881.986798] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[ 1881.989755] scsi host0: usb-storage 1-1.3:1.0
[ 1883.035991] scsi 0:0:0:0: Direct-Access     SanDisk  Ultra USB 3.0    1.00 PQ: 0 ANSI: 6
[ 1883.037016] sd 0:0:0:0: Attached scsi generic sg0 type 0
[ 1883.037906] sd 0:0:0:0: [sda] 120127488 512-byte logical blocks: (61.5 GB/57.3 GiB)
[ 1883.038876] sd 0:0:0:0: [sda] Write Protect is off
[ 1883.038890] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[ 1883.039290] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[ 1883.059968]  sda: sda1
[ 1883.062485] sd 0:0:0:0: [sda] Attached SCSI removable disk

* Output of `ls /dev`
autofs		 loop3		     ram3     tty16  tty41  ttyAMA0
block		 loop4		     ram4     tty17  tty42  ttyprintk
bsg		 loop5		     ram5     tty18  tty43  uhid
btrfs-control	 loop6		     ram6     tty19  tty44  uinput
bus		 loop7		     ram7     tty2   tty45  urandom
cachefiles	 mapper		     ram8     tty20  tty46  vc-mem
char		 mem		     ram9     tty21  tty47  vchiq
console		 memory_bandwidth    random   tty22  tty48  vcio
cpu_dma_latency  mmcblk0	     raw      tty23  tty49  vcs
cuse		 mmcblk0p1	     rfkill   tty24  tty5   vcs1
disk		 mmcblk0p2	     sda      tty25  tty50  vcs2
fb0		 mqueue		     sda1     tty26  tty51  vcs3
fd		 net		     serial1  tty27  tty52  vcs4
full		 network_latency     sg0      tty28  tty53  vcs5
fuse		 network_throughput  shm      tty29  tty54  vcs6
gpiochip0	 null		     snd      tty3   tty55  vcsa
gpiochip1	 ppp		     stderr   tty30  tty56  vcsa1
gpiomem		 ptmx		     stdin    tty31  tty57  vcsa2
hwrng		 pts		     stdout   tty32  tty58  vcsa3
i2c-1		 ram0		     tty      tty33  tty59  vcsa4
initctl		 ram1		     tty0     tty34  tty6   vcsa5
input		 ram10		     tty1     tty35  tty60  vcsa6
kmsg		 ram11		     tty10    tty36  tty61  vcsm
log		 ram12		     tty11    tty37  tty62  vhci
loop-control	 ram13		     tty12    tty38  tty63  watchdog
loop0		 ram14		     tty13    tty39  tty7   watchdog0
loop1		 ram15		     tty14    tty4   tty8   zero
loop2		 ram2		     tty15    tty40  tty9

**Comment by selcukercan** [comment]
@lgulich you need to restart your duckiebot.

**Comment by lgulich** [comment]
I have tried so several times, unfortunately this did not help

**Comment by selcukercan** [comment]
@lgulich then could you try using a different usb?

**Comment by lgulich** [comment]
I have resolved the problem using Li Cliffs trick from slack: https://duckietown.slack.com/archives/CD5QXCC5P/p1540470360000100?thread_ts=1540469746.000100&cid=CD5QXCC5P
