### ISSUE TITLE
Demo System ID, Step 9: UnboundLocalError observed 

### ISSUE THREAD

**Issue by BensonKuan** [duckietown/docs-opmanual_duckiebot#123]
### Context

*What step were you trying in the documentation?*
Part D - Demo System ID, Step 9

*What command line were you running?*
roslaunch calibration calibration.launch veh:=yellowbot  path:=/home/benson/Documents/ETH_MSRC/Sem1/AMoD/duckietown_sysid/

### Problem

*What happened?*
I get following:
```
... logging to /home/benson/.ros/log/b847150c-d7c2-11e8-aa87-94b86dfa0f3c/roslaunch-Exia-15195.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Exia.local:37759/

SUMMARY
========

CLEAR PARAMETERS
 * /kinematic_calibration/

PARAMETERS
 * /kinematic_calibration/path: /home/benson/Docu...
 * /kinematic_calibration/veh: yellowbot
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    kinematic_calibration (calibration/kinematic_calibration.py)

auto-starting new master
process[master]: started with pid [15205]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b847150c-d7c2-11e8-aa87-94b86dfa0f3c
process[rosout-1]: started with pid [15218]
started core service [/rosout]
process[kinematic_calibration-2]: started with pid [15227]
Traceback (most recent call last):
  File "/home/benson/Documents/ETH_MSRC/Sem1/AMoD/duckietown/Software/catkin_ws/src/05-teleop/calibration/src/kinematic_calibration.py", line 946, in <module>
    calib=calib()
  File "/home/benson/Documents/ETH_MSRC/Sem1/AMoD/duckietown/Software/catkin_ws/src/05-teleop/calibration/src/kinematic_calibration.py", line 53, in __init__
    self.H = self.load_homography()
  File "/home/benson/Documents/ETH_MSRC/Sem1/AMoD/duckietown/Software/catkin_ws/src/05-teleop/calibration/src/kinematic_calibration.py", line 101, in load_homography
    return np.array(data['homography']).reshape((3, 3))
UnboundLocalError: local variable 'data' referenced before assignment
================================================================================REQUIRED process [kinematic_calibration-2] has died!
process has died [pid 15227, exit code 1, cmd /home/benson/Documents/ETH_MSRC/Sem1/AMoD/duckietown/Software/catkin_ws/src/05-teleop/calibration/src/kinematic_calibration.py __name:=kinematic_calibration __log:=/home/benson/.ros/log/b847150c-d7c2-11e8-aa87-94b86dfa0f3c/kinematic_calibration-2.log].
log file: /home/benson/.ros/log/b847150c-d7c2-11e8-aa87-94b86dfa0f3c/kinematic_calibration-2*.log
Initiating shutdown!
================================================================================
[kinematic_calibration-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

*What did you expect to happen?*
Data to be present but it doesnt appear so

### System information

Duckietown version: 

- [x] DT18 
- [ ] DT17

Duckiebot version: 

- [x] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 18.04, virtual machine
- [x] Ubuntu 16.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___

**Comment by manish-pra** [comment]
It is not able to find the path of the calibration file.
Can you tell me what is inside your this directory "/home/benson/Documents/ETH_MSRC/Sem1/AMoD/duckietown_sysid/"

**Comment by BensonKuan** [comment]
I have the following files inside
default.yaml                 
yellowbot.yaml.disabled.003
yellowbot_calibration.bag    
yellowbot.yaml.disabled.004
yellowbot.yaml               
yellowbot.yaml.disabled.005
yellowbot.yaml.disabled.000  
yellowbot.yaml.disabled.006
yellowbot.yaml.disabled.001  
yellowbot.yaml.disabled.007
yellowbot.yaml.disabled.002

**Comment by BensonKuan** [comment]
I managed to solve it. Apparently yellowbot.yaml is a name that is used by all three intrinsic, extrinsic and kinematic which resulted in it being overwritten when it was all the files in the folder were extracted and copied over to the computer with the inclusion of the \  before the curly bracket

with extraction (do not use)
`scp -r ROBOT_NAME:/data/config/calibrations/\{kinematics,camera_extrinsic,camera_intrinsic\} ~/duckietown_sysid`

without extraction (please use this)
`scp -r ROBOT_NAME:/data/config/calibrations/{kinematics,camera_extrinsic,camera_intrinsic\} ~/duckietown_sysid`

When I did not extract the files out but kept them in their own folder, the calibration code was able to run.
