### ISSUE TITLE
wrong permission on calibration file

### ISSUE THREAD

**Issue by gibernas** [duckietown/docs-opmanual_duckiebot#188]
### Context

Demo Sysid:
http://docs.duckietown.org/DT19/opmanual_duckiebot/out/demo_sysid.html

Step 6:

    laptop $ scp -r ROBOT_NAME:/data/config/calibrations/ ~/duckietown_sysid

### Problem

kinematics file (*_kinematic_drive.yaml) has not read permission on *g* and *u*, so can't be copied from local computer.

### System information

Duckietown version: 

- [x ] DT18 

Duckiebot version: 

- [x] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [x ] Ubuntu 16.04, native installation

**Comment by tanij** [comment]
System ID has been updated and this issue should be solved
