### ISSUE TITLE
Circleci not reporting status

### ISSUE THREAD

**Issue by tanij** [duckietown/docs-opmanual_duckiebot#197]
CircleCI is not reporting on all status when merging PRs in docs-opmanual-duckiebot

![image](https://user-images.githubusercontent.com/17256784/55911493-17686e80-5be1-11e9-80f8-6ff3cfcb9fde.png)

**Comment by AndreaCensi** [comment]
CircleCI problem: https://status.circleci.com/

reopen if persists

Probably need to make one more commit to restart things.
