### ISSUE TITLE
Duckiebot Wifi Connection to network without password?

### ISSUE THREAD

**Issue by thomaskwok91** [duckietown/docs-opmanual_duckiebot#262]
### Context

*What step were you trying in the documentation?*

Duckiebot initalization stage

*What command line were you running?*

dts init_sd_card --hostname [hostname] --wifi myuninetwork

### Problem

My university has a wifi network that does not require a password, they may ask for identification once you are logged onto the network but the network itself doesn't have a set password for everyone. So I was curious, how do I create a micro SD chip that would be logged onto the wifi network that doesn't have a password?

I tried the above command but it said the --wifi myuninetwork is incorrect, which I assume because it doesn't recognize that format since there is no password. Is there a way to fix this?

### System information

Duckietown version: 

Daffy newest one
- [ ] DT18 
- [ ] DT17

Duckiebot version: 

Daffy newest one

- [ ] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [x] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

**Comment by liampaull** [comment]
@afdaniele should be closed shouldn't it?

**Comment by afdaniele** [comment]
Yes, this was solved in https://github.com/duckietown/duckietown-shell-commands/commit/93a2ffd28f82f4129440d00cc7da4311b241bfbe
