### ISSUE TITLE
Camera and Duckiemove not working (May be container but not sure)

### ISSUE THREAD

**Issue by thomaskwok91** [duckietown/docs-opmanual_duckiebot#263]
### Context

*What step were you trying in the documentation?*

Currently following Making your Duckiebot move step and See what your Duckiebot sees

*What command line were you running?*

For the duckiebot move I ran:
dts duckiebot keyboard_control [hostname] --base_image duckietown/dt-core:daffy-amd64

Also went to:
http://[hostname].local/mission-control

For the camera I ran:
dts start_gui_tools [hostname] --base_image duckietown/dt-core:daffy-amd64
rqt_image_view

### Problem

*What happened?*

For the duckiebot move command, I am able to see the keyboard GUI and when I click the arrows on my keyboard I see them turn yellow on the GUI. But I don't see the duckiebot move at all, so I think something may be wrong here and the signal isn't being sent or something. I read on other threads, this may be something like a missing container as I don't see the roscore or joy-cli container when I looked at my dashboard, but I also don't know how to go about installing them.

For the duckiebot move through the dashboard, I am able to take control, see the screen turn yellow, also see that the bridge is connected, but again if I move my keyboard the duckiebot isn't moving at all.

For the camera I entered the command and see the rqt image view GUI but I am unable to see anything in the camera, nor is there anything that shows when I click the dropdown menu. Again could be a container issue.

### System information

Duckietown version: 

Daffy = Newest version
- [ ] DT18 
- [ ] DT17

Duckiebot version: 

Daffy = Newest version
- [ ] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [x] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

**Comment by liampaull** [comment]
Hi @thomaskwok91, please be careful to follow the `DT19` instructions. It looks like you are following the ones for `daffy`.
