### ISSUE TITLE
[known problem] "Bad archive" when using `dts init_sd_card`

### ISSUE THREAD

**Issue by AndreaCensi** [duckietown/docs-opmanual_duckiebot#31]
Resolution: It usually means that you don't have enough disk space on your laptop.

Reported by @AleksandarPetrov 

![screenshot from 2018-10-02 09-47-47](https://user-images.githubusercontent.com/81052/46342130-4a321880-c63a-11e8-9ae7-f72ff8688757.png)

TODO: have the script check that there is enough disk space before starting the installation.

**Comment by AndreaCensi** [comment]
Addressed by https://github.com/duckietown/duckietown-shell-commands/pull/21

**Comment by manish-pra** [comment]
I am still getting this error.

**Comment by manish-pra** [comment]
I deleted the duckietown files in my tmp folder and restart my computer it solved the issue.

**Comment by AndreaCensi** [comment]
I believe the new version has more checks to solve this issue.
