### ISSUE TITLE
Install/update duckietown-shell

### ISSUE THREAD

**Issue by lapandic** [duckietown/docs-opmanual_duckiebot#37]
### Context and Problem

I wanted to update the duckietown-shell (also had the same issue when installing for the first time, step 1.5.4. at http://docs.duckietown.org/DT18/opmanual_duckiebot/out/laptop_setup.html)
by running this command
`dzenan:~$ pip install --user -U --no-cache-dir duckietown-shell==3.0.2
Traceback (most recent call last):
  File "/home/dzenan/.local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal`
Same error occurred when using virtual environment. 

I tried to execute with sudo because here it uses it: https://github.com/duckietown/duckietown-shell
Also got an error. This error may be because of python2.7 and python3.5 installed on the system so I tested following two commands
`dzenan:~$ pip2 install --user -U --no-cache-dir duckietown-shell==3.0.2`
`dzenan:~$ sudo pip2 install --user -U --no-cache-dir duckietown-shell==3.0.2`
The last one finally worked. 

Should we change the command in documentation?

### System information

Duckietown version: DT18

Duckiebot version: DB18

Computer OS: Ubuntu 16.04LTS

### Additional notes

Both Python 2.7 and Python 3.5 are installed on the system

**Comment by AndreaCensi** [comment]
I fixed the instructions - should never use `sudo`.

**Comment by AndreaCensi** [comment]
also fixing to always use `pip2`

**Comment by AndreaCensi** [comment]
@lapandic  see https://github.com/pypa/pip/issues/5253

My guess is botched installation.

**Comment by lapandic** [comment]
Thanks @AndreaCensi. It works now.
I only had a problem to install it in virtualenv:
`(dts) dzenan:~$ pip install --user -U --no-cache-dir duckietown-shell==3.0.6
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`
Without virtualenv there are no problems, but I guess it is not expected to be installed within the virtualenv.

**Comment by AndreaCensi** [comment]
Yeah that's annoying, you cannot use --user in the virtualenv.

**Comment by renatojmsantos** [comment]
Hi! I can't install on mac os...

i tried every times... i have python3.... 

How can i use DTS? 

it appears this message:

"
There is an updated duckietown-shell available.

  You have: 3.0.30

 available: 5.1.22 

You should update the shell using `pip`.        
        
        
Waiting 3 seconds to give you time to read the message.

dts :  duckietown-shell-commands requires Python 3.6 and later.
    :  Detected 2.7.15 (default, Aug 16 2018, 14:17:09) 
    :  [GCC 6.4.0].

dts :  Please report that you are using:
    :  
    :  duckietown-shell: 3.0.30
    :  python: "2.7.15 (default, Aug 16 2018, 14:17:09) \n[GCC 6.4.0]"
"
