### ISSUE TITLE
SD-Card Initialization Failure 

### ISSUE THREAD

**Issue by selcukercan** [duckietown/docs-opmanual_duckiebot#38]
### Context

*What step were you trying in the documentation?*
Initializing the SD-card 

*What command line were you running?*
dts init_sd_card

### Problem

*What happened?*
Failed to initialize

*What did you expect to happen?*
Successful initialization

### System information

Duckietown version: *[DT18, DT17, ...]*
Irrelevant

Duckiebot version: *[DB18, DB17, ...]*
DB18

Computer OS: *[Ubuntu 18.x, OS X, etc.]*
Ubuntu 16.04

### Additional notes

Add any other notes about the problem here.
Why does the initialization procedure try to access [ROBOT_NAME].local (ata.local)?

### Screenshots
![errror](https://user-images.githubusercontent.com/23402981/46374313-b8092f00-c690-11e8-8cd5-a869bb0e2e08.png)

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

**Comment by selcukercan** [comment]
I did have internet connection on my laptop while executing this command.

**Comment by AndreaCensi** [comment]
@selcukercan did you have the variable DOCKER_HOST set up?

**Comment by selcukercan** [comment]
Having DOCKER_HOST set-up was indeed the problem, now it flashes without any issue

**Comment by AndreaCensi** [comment]
The script now checks this condition.
