### ISSUE TITLE
connecting with protected university wifi

### ISSUE THREAD

**Issue by meliscan1** [duckietown/docs-opmanual_duckiebot#403]
### Context

*What step were you trying in the documentation?*
UNIT-C19
19.1

*What command line were you running?*

### Problem

*What happened?*
I have problem with connecting protected university wifi (wireless), I have wifi account and when I try to connect these information its not working.

*What did you expect to happen?*
I would like to connect wireless with my wifi account

### System information

Duckietown version: 

- [ ] DT18 
- [ ] DT17

Duckiebot version: 

- [ ] DB18
- [ ] DB17
- [ ] other: ___DB21M

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___  22.04 native installation
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots
![image](https://user-images.githubusercontent.com/109961075/188625627-ed5399f4-7d52-498b-b5bf-5127714dd8b7.png)

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

**Comment by liampaull** [comment]
This is a complex problem that is going to be based on the specific network setup. Very possible that your network does not allow ssh or discovery tools such as avahi. You would have to contact your network administrator to solve this problem.
