### ISSUE TITLE
Pip package clash when installing duckietown-shell

### ISSUE THREAD

**Issue by AleksandarPetrov** [duckietown/docs-opmanual_duckiebot#54]
### Context

*What step were you trying in the documentation?*
Laptop Setup

*What command line were you running?*
`$ pip install --no-cache-dir -U --user duckietown-shell`

### Problem

*What happened?*
Got the following error:
`pycollada 0.4 has requirement python-dateutil==1.5, but you'll have python-dateutil 2.5.3 which is incompatible.`
On attempt to install `python-dateutil==1.5` with `pip` it did not allow me as that would break `jupyter` which I also have.

*What did you expect to happen?*
To install `duckietown-shell` with no errors.

### System information

Computer OS: *[Ubuntu 18.x, OS X, etc.]*
Ubuntu 16.04

**Comment by AndreaCensi** [comment]
@AleksandarPetrov it looks like the conflict is between `jupyter` and `pycollada`. 

The DT software does not require a particular version of dateutil.

**Comment by AleksandarPetrov** [comment]
I am not sure how `dateutil` fits in this...
Is there any way to force pip to install it despite this conflict?

**Comment by AndreaCensi** [comment]
Are you on Ubuntu? Try installing python-dateutil

**Comment by AleksandarPetrov** [comment]
Now it works, I did have `python-dateutil`. Maybe some of the updates fixed it.
