### ISSUE TITLE
Pinging the Duckiebot is misleading for initialization success

### ISSUE THREAD

**Issue by AleksandarPetrov** [duckietown/docs-opmanual_duckiebot#55]
### Context

*What step were you trying in the documentation?*
In Duckiebot Initialization:

> You know that your Pi has successfully booted when you are able to ping your robot with the command bellow or with some method in Unit A-6 - Networking, a.k.a. the hardest part...
> `$ ping hostname.local`

### Problem

That is true but not quite the important part. `hostname.local` is pingable when the robot boots, but we should wait until all the containers are (pulled and) started. If someone pings it and then immediately shuts the bot off, they will likely interrupt the initialization of the containers.

Maybe we should instead give a command that checks if the whole initialization is complete.

**Comment by AndreaCensi** [comment]
True.

Ideally, we blink the lights.

**Comment by AleksandarPetrov** [comment]
Oh, haven't ever seen that happening...
