### ISSUE TITLE
Launching "duckietown/rpi-duckiebot-base:master18" error

### ISSUE THREAD

**Issue by selcukercan** [duckietown/docs-opmanual_duckiebot#76]
### Context

*What were you doing? Where were you in the manual?*

Wheel calibration section of the manual. But it is a more generic docker issue.

### Command line

*What command line did you run?*

     $ docker -H ata.local run -it --net host --privileged  duckietown/rpi-duckiebot-base:master18
     
What is the value of the `DOCKER_HOST` variable?

```
Put here output of 

    echo $DOCKER_HOST

ata.local

```

###  Problem

*What did you expect?*

Base container to be started and command line to switch to duckietown root of the robot.

*What happened instead?*

Image is created [ but not running], cli to robot is not launched successfully:

#### Software diagnostics

*What other containers are running or stopped?*

```
Put here the output of: 

    $ docker -H YOURDUCKIEBOT.local ps -a -q

9cc780f94ae1
457ad78b8e9f
d7d2c20f3fa5
970ba889d975
d89adf98584d
f80877b88781
dfe38e31d775
096d320ff53d
da7880ced620
015a76308c7c

   
```

#### Hardware diagnostics

What does the `rpi-health` diagnostics say?
(You can find these in Portainer, or at `http://duckiebot.local:8085`.)

- [] I don't know because I didn't look.

or 

- [ ] Error: PI is throttled
- [ ] Error: Under-voltage
- [ ] Error: Frequency capped
- [ ] Warning: PI throttling occurred in the past.
- [ ] Warning: Under-voltage occurred in the past.
- [ ] Warning: Frequency capped occurred in the past.
- [X ] None of the above

### Error report

*Please report here the **complete** error message. You can find the container log in the Portainer interface.*  

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/ros_entrypoint.sh\": stat /ros_entrypoint.sh: no such file or directory": unknown.
```
**Note that the last error is *never* the error that caused the issue. You have to SCROLL UP and find the FIRST error in the log.**

### Other notes

*Other comments?*

**Comment by selcukercan** [comment]
@AndreaCensi This error still persists, I had this while recently while repeating the camera calibration procedure

**Comment by davidoort** [comment]
This is a recurring issue! I encountered it when running the built container for the lane following exercise on my computer and on the J44 lab computer which has a different Ubuntu version. According to @selcukercan the only solution at the moment is flashing the SD card again.

**Comment by selcukercan** [comment]
To be more precise reflashing resolved this issue, i don't claim it to be the only solution :)

**Comment by liampaull** [comment]
This should all be solved with recent updates. For the record, let's never use the DOCKER_HOST env variable it only causes confusion and problems.
