### ISSUE TITLE
Error when trying to do the extrinsic calibration: tls: oversized record received with length 20527

### ISSUE THREAD

**Issue by alessandromorra** [duckietown/docs-opmanual_duckiebot#91]
### Context

*What step were you trying in the documentation?*

10.3 Perform intrinsics calibration

*What command line were you running?*

dts calibrate kleinesentlein

### Problem

*What happened?*

When I press enter after the intrinsic calibration I get following mistake:

tls: oversized record received with length 20527

and I cannot do the calibration

*What did you expect to happen?*

the calibration to work...?

### System information

dts version 3.0.18

Duckietown version: 

- [X] DT18 
- [ ] DT17

Duckiebot version: 

- [X] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [X] Ubuntu 16.04, native installation
- [ ] Ubuntu 18.04, virtual machine
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

![issue_with_calibration](https://user-images.githubusercontent.com/32458198/47079979-0e38af00-d207-11e8-9ec1-e3d9f9349afd.JPEG)

![error_2](https://user-images.githubusercontent.com/32458198/47080403-2a891b80-d208-11e8-91bf-24f8e43fd9e6.jpeg)

**Comment by liampaull** [comment]
@mweiss17 did you ever solve this ?

**Comment by mcp10** [comment]
I'm having the same issue with my duckiebot.

I tried to do the calibration with an other duckiebot and seed to work fine. It must be something with the bot. 

Stuck here too..

Thanks for any help!

**Comment by alessandromorra** [comment]
Observation: I temporarily solved it by launching the `dts calibrate` command from another computer… I think my other programs on Linux interfere with the duckietown shell, as my friend’s computer had nothing else installed (only a speculation)...

**Comment by cyuanli** [comment]
I am having the same issue. After the intrinsic calibration, once I press Enter the `ros-picam` container shuts down. Nothing in the logs, no error or warning or goodbye. The local terminal (duckietown shell) shows `tls: oversized record received with length 20527`.

**Comment by AleksandarPetrov** [comment]
@liampaull @mcp10 @cyuanli 

If Docker exits with the above error when running remote comamnds, the most likely reason is different versions of Docker on your computer and Duckiebot. You can check that by running docker version on both devices. If that is indeed the case, you need to upgrade the Docker binaries on your computer. To do that, follow the official instructions [here](https://docs.docker.com/install/linux/docker-ce/ubuntu/).

@alessandromorra please close this if the issue is resolved

**Comment by alessandromorra** [comment]
@AleksandarPetrov Thanks a lot! 

This solved my issue.
